//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.chienvh {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.chienvh.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string langVietnamese {
            get {
                return ResourceManager.GetString("langVietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string lbSelect {
            get {
                return ResourceManager.GetString("lbSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More.
        /// </summary>
        internal static string ltlAddMore {
            get {
                return ResourceManager.GetString("ltlAddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string ltlDistrict {
            get {
                return ResourceManager.GetString("ltlDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string ltlDivision {
            get {
                return ResourceManager.GetString("ltlDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        internal static string ltlDonation {
            get {
                return ResourceManager.GetString("ltlDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity.
        /// </summary>
        internal static string ltlequity {
            get {
                return ResourceManager.GetString("ltlequity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Year.
        /// </summary>
        internal static string ltlFinancialYear {
            get {
                return ResourceManager.GetString("ltlFinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.O.B.
        /// </summary>
        internal static string ltlGOB {
            get {
                return ResourceManager.GetString("ltlGOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOB Foriegn Curruency.
        /// </summary>
        internal static string ltlGOBForiegnCurruency {
            get {
                return ResourceManager.GetString("ltlGOBForiegnCurruency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Agnecy.
        /// </summary>
        internal static string ltlImplementingAgency {
            get {
                return ResourceManager.GetString("ltlImplementingAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Investment.
        /// </summary>
        internal static string ltlInitialInvestment {
            get {
                return ResourceManager.GetString("ltlInitialInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        internal static string ltlLoan {
            get {
                return ResourceManager.GetString("ltlLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective, Goals &amp; Beneficiary.
        /// </summary>
        internal static string ltlObjectivesGoalsBeneficiary {
            get {
                return ResourceManager.GetString("ltlObjectivesGoalsBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Mandatory.
        /// </summary>
        internal static string ltlOtherMandatory {
            get {
                return ResourceManager.GetString("ltlOtherMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string ltlOthers {
            get {
                return ResourceManager.GetString("ltlOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnFinacneForeignCurrency.
        /// </summary>
        internal static string ltlOwnFinacneForeignCurrency {
            get {
                return ResourceManager.GetString("ltlOwnFinacneForeignCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Finance.
        /// </summary>
        internal static string ltlOwnFinance {
            get {
                return ResourceManager.GetString("ltlOwnFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Commission Dept.
        /// </summary>
        internal static string ltlPlanningCommission {
            get {
                return ResourceManager.GetString("ltlPlanningCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Code.
        /// </summary>
        internal static string ltlProjectCode {
            get {
                return ResourceManager.GetString("ltlProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Duration.
        /// </summary>
        internal static string ltlProjectDuration {
            get {
                return ResourceManager.GetString("ltlProjectDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string ltlProjectEndDate {
            get {
                return ResourceManager.GetString("ltlProjectEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string ltlProjectName {
            get {
                return ResourceManager.GetString("ltlProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string ltlProjectStartDate {
            get {
                return ResourceManager.GetString("ltlProjectStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry.
        /// </summary>
        internal static string ltlRaisingMinistry {
            get {
                return ResourceManager.GetString("ltlRaisingMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thana.
        /// </summary>
        internal static string ltlThana {
            get {
                return ResourceManager.GetString("ltlThana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Corporation/Municipility/Thana.
        /// </summary>
        internal static string ltlThanaAll {
            get {
                return ResourceManager.GetString("ltlThanaAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string ltlTotal {
            get {
                return ResourceManager.GetString("ltlTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Foriegn Currency.
        /// </summary>
        internal static string ltlTotalForiegnCurrency {
            get {
                return ResourceManager.GetString("ltlTotalForiegnCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string mnuContactUs {
            get {
                return ResourceManager.GetString("mnuContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string mnuHome {
            get {
                return ResourceManager.GetString("mnuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string mnuIntroduction {
            get {
                return ResourceManager.GetString("mnuIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string mnuProduct {
            get {
                return ResourceManager.GetString("mnuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string rdbFemale {
            get {
                return ResourceManager.GetString("rdbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string rdbMale {
            get {
                return ResourceManager.GetString("rdbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string rdTbArea {
            get {
                return ResourceManager.GetString("rdTbArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        internal static string rdTbBasicInfo {
            get {
                return ResourceManager.GetString("rdTbBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment type.
        /// </summary>
        internal static string rdTbInvestmenttype {
            get {
                return ResourceManager.GetString("rdTbInvestmenttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yearly expense.
        /// </summary>
        internal static string rdTbYearlyExpense {
            get {
                return ResourceManager.GetString("rdTbYearlyExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project Creation.
        /// </summary>
        internal static string titleNewProject {
            get {
                return ResourceManager.GetString("titleNewProject", resourceCulture);
            }
        }
    }
}
