<%@ Page Title="" Language="C#" MasterPageFile="~/InvexiaMaster.Master" AutoEventWireup="true" CodeBehind="FeesCollectionUI.aspx.cs" Inherits="InovexiaEBS.SchoolManagement.FeesCollecionUI" %>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
        
    <style>
        
        
                        .divColorb {
                            background-color:  #e6e6ff;
                            /*color: grey;*/
                        }

                        .batchbutton {
                            color: #006699;
                        }

                        .labelbatchcheck {
                           /*// color: red;*/
                            padding-left: 0px;
                            padding-top: 20px;
                        }

                        .dropdown {
                            width: 350px;
                        }

                       
    </style>

    

       <div class="row" id="MasterPanel" runat="server" >
             <div class="col-lg-12">
                 
                <div class="breadcrumb fontcolordiv" style="background-color: #b3b3b3"  >
                                                    <li class="breadcrumb-item" ><a href="#">Home</a></li>
                                                    <li class="breadcrumb-item"><a href="#">Fees</a></li>
                                                    <li class="breadcrumb-item"><a href="#">Fees Collection</a></li>
                                                 
                                                    
                   </div>

              <div class="alert alert-dark"  id="alertpayment2" runat="server" style="text-decoration: beige ; font-family: cursive" role="alert">
               Fees Collection Saved Successfully!
            </div>
                 
                 
              <div class="alert alert-warning"  id="alertpayment1" runat="server" style="text-decoration: beige ; font-family: cursive" role="alert">
               Updated Successfully!
            </div>   
                
           
                 
                  
                 <div class="row " id="divpdetails" runat="server" style="font-family: serif">
                     
                       <div class="col-lg-12">
                                <div class="card">
           
                                  <div class="card-body divColorb">
                                    <h3 style="font-family: fantasy">Fees Collection</h3>
                                                      
                                       
                                            <div class="list-divider"></div>
                                                    Fields with<span style="color: red">*</span> are required
                                                    <br/>
                                                <br/>
                                  
                                                <div class="row">
                                                                            
                                                <div class="col-md-6" >
                                                 
                                                <asp:Label ID="Label2" runat="server" Text="Reference No"  Font-Bold="true" ></asp:Label>&nbsp;&nbsp;
                                                   <br/>
                                                
                                                 
                                                <asp:TextBox ID="txtrefno" runat="server" CssClass="form-control" ReadOnly="True" Width="350px" placeholder="Autogenerated"></asp:TextBox>
                                               
                                                    
                                                <br/>
                                               
                                        </div> 
                                                <br/>
                                                    <br/>
                                                               
                                                <div class="col-md-6"  >
                                                    
                                                   
                                                <asp:Label ID="Label5" runat="server" Text="Date"  Font-Bold="true"></asp:Label>
                                                        <span style="color: red">*</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                    
                                                    <br/>
                                                        <telerik:RadDatePicker ID="ddlfeedate" Class="form-control" runat="server" AutoPostBack="false" Culture="en-US"  
                                                               MaxDate="3000-01-01" MinDate="1000-01-01" ShowPopupOnFocus="True" Style="background-color: #FFFFFF; font-weight: 700; 
                                                              color: #FF0000;" Width="350px">
                                                                <Calendar UseColumnHeadersAsSelectors="False" UseRowHeadersAsSelectors="False" runat="server"  SelectionMode="Day" 
                                                                   ShowLines="True">
                                                                                         
                                                                                </Calendar>
                                                                                <DateInput AutoPostBack="false" DateFormat="d/MM/yyyy" DisplayDateFormat="d/MM/yyyy" LabelWidth="40%" runat="server">
                                                                                </DateInput>
                                                                           
                                                           </telerik:RadDatePicker>
                                                    <br/>
                                                          <asp:Label ID="lblfeedate" runat="server" CssClass="labelbatchcheck" Text="*Future Dates are not allowed" ForeColor="red"></asp:Label><br/>  
                                                          <asp:Label ID="lblfeedate1" runat="server" CssClass="labelbatchcheck" Text="*At max two Previous days are allowed" ForeColor="orange"></asp:Label>  
                                                      <%--  <asp:RequiredFieldValidator ID="rfvddlclass" ControlToValidate="ddlclass" runat="server" ForeColor="red" ErrorMessage="*Required" ValidationGroup="batchvalidation"  SetFocusOnError="True"></asp:requiredfieldvalidator>    --%>
                     
                                              </div>
                                            
                                                </div>
                                            
                                                                                           
                                                <div class="row">
                                                     
                                                     <div class="col-md-6" >
                                                     
                                                <asp:Label ID="Label1" runat="server" Text="Student"  Font-Bold="true" ></asp:Label>
                                                    <span style="color: red">*</span>&nbsp;&nbsp;&nbsp;&nbsp;
                                                <br/>
                                                      
                                                 <telerik:RadComboBox ID="ddlstudent"  runat="server" DropDownCssClass="widthClass dropdown"  
                                                            EmptyMessage="Select Student" EnableLoadOnDemand="True" Filter="Contains" Height="100%"
                                                            HighlightTemplatedItems="True" Width="67%" Skin="Silk" Style="background-color: #339966;"
                                                            AutoPostBack="False" OnItemsRequested="ddlstudent_OnItemsRequested">
                                                             <HeaderTemplate>
                                                                <table cellpadding="0" cellspacing="0">
                                                                    <tr>

                                                                        <td>StudentID. Name</td>

                                                                    </tr>
                                                                </table>
                                                            </HeaderTemplate>
                                                        </telerik:RadComboBox>
                                                        <br/>
                                                          <asp:RequiredFieldValidator ID="rfvddlstudent" ControlToValidate="ddlstudent" runat="server" ForeColor="red" ErrorMessage="*Required" ValidationGroup="feescollectionvalidation"  SetFocusOnError="True"></asp:requiredfieldvalidator>
                                                        <asp:Label ID="lblstudent" runat="server" CssClass="labelbatchcheck" Text="* Student Cannot be Updated" ForeColor="orange"></asp:Label>  
                                                         </div>
                                                      <br/>
                                                    <br/>
                                                      
                                                         <div class="col-md-6">
                                                             
                                                        
                                                <asp:Label ID="Label3" runat="server" Text="Collection Head"  Font-Bold="true" ></asp:Label><%--&nbsp;&nbsp;--%>
                                                        <span style="color: red">*</span>&nbsp;&nbsp;&nbsp;&nbsp;               
                                                        <br/>
                                                         

                                                
                                                 <telerik:RadComboBox ID="ddlfeetype"  runat="server" DropDownCssClass="widthClass"  
                                                            EmptyMessage="Fee Type" EnableLoadOnDemand="True" Filter="Contains" Height="100%"
                                                            HighlightTemplatedItems="True" Width="67%" Skin="Silk" Style="background-color: #339966;"
                                                            AutoPostBack="False" OnItemsRequested="ddlfeetype_OnItemsRequested">
                                                           
                                                        </telerik:RadComboBox>
                                               <br/>
                                                               <asp:RequiredFieldValidator ID="rfvddlfeetype" ControlToValidate="ddlfeetype" runat="server" ForeColor="red" ErrorMessage="*Required" ValidationGroup="feescollectionvalidation"  SetFocusOnError="True"></asp:requiredfieldvalidator>
                                                     <br/>

                                                     </div>  
                                                        
                                              
                                                    </div>
                                                   
                                                      
                                                   
                                      <br/>
                                        <div class="row">
                                                     
                                                    
                                                                  
                                                     <div class="col-md-6" >
                                                    
                                                <asp:Label ID="Label7" runat="server" Text="Collection Mode"  Font-Bold="true" ></asp:Label>
                                                <span style="color: red">*</span>&nbsp;&nbsp;&nbsp;&nbsp;      
                                                
                                                <br/>
                                                 <telerik:RadComboBox ID="ddlpaymode"  runat="server" DropDownCssClass="widthClass"  
                                                            EmptyMessage="Payment Method" EnableLoadOnDemand="True" Filter="Contains" Height="100%"
                                                            HighlightTemplatedItems="True" Width="67%" Skin="Silk" Style="background-color: #339966;"
                                                            AutoPostBack="False" OnItemsRequested="ddlpaymode_OnItemsRequested">
                                                           
                                                        </telerik:RadComboBox>
                                               <br/>
                                                            <asp:RequiredFieldValidator ID="rfvddlpaymode" ControlToValidate="ddlpaymode" runat="server" ForeColor="red" ErrorMessage="*Required" ValidationGroup="feescollectionvalidation"  SetFocusOnError="True"></asp:requiredfieldvalidator>
                                                     </div>                        
                                                      
                                                   
                                                     <div class="col-md-6" >
                                                     
                                                     
                                                    <asp:Label ID="Label4" runat="server" Text="Amount"  Font-Bold="true" ></asp:Label>
                                                    <span style="color: red">*</span>&nbsp;&nbsp;&nbsp;&nbsp;
                                                <br/>
                                                 <asp:TextBox ID="txtamount" runat="server" CssClass="form-control" Width="67%" ></asp:TextBox>
                                                       
                                                      
                                                          <asp:Label ID="Label6" runat="server" CssClass="labelbatchcheck"></asp:Label>  
                                                         
                                                          
                                                  <%--<br/>--%>
                                                           <asp:RequiredFieldValidator ID="rfvtxtamount" ControlToValidate="txtamount" runat="server" ForeColor="red" ErrorMessage="*Required" ValidationGroup="feescollectionvalidation"  SetFocusOnError="True"></asp:requiredfieldvalidator>
                                                    </div>

                                                      
                                                   
                                                                            
                                                </div>
                                  <%--    <asp:HiddenField ID="hfbatchcheck" runat="server" EnableViewState="True" />--%>
                                    
                                      <div class="row">
                                          <div class="col-md-6" >
                                                     
                                                         
                                                <asp:Label ID="Label9" runat="server" Text="Narration"  Font-Bold="true" ></asp:Label>
                                                    <span style="color: red">*</span>&nbsp;&nbsp;&nbsp;&nbsp;
                                                <br/> 
                                                 <asp:TextBox ID="txtnarrationpayment" runat="server" CssClass="form-control"  Width="67%" ></asp:TextBox>
                                                    
                                                    </div>

                                                 
                                      </div>   
                                      <br/> 
                                      <br/>  
                                      <div style="float: right">
                                          
                                           <asp:Button ID="btnuppayment" CssClass="btn btn-warning" runat="server" 
                                                       Text="Update" OnClick="btnuppayment_OnClickupdatepayment"
                                                     />
                                                 <asp:Button ID="btnsavePay" CssClass="btn btn-primary" runat="server" CausesValidation="True" 
                                                     ValidationGroup="feescollectionvalidation"  Text="Save" OnClick="SavePayment"
                                                     />
                                          
                                           <asp:Button ID="btnaddan" CssClass="btn btn-mint" runat="server" 
                                                       Text="Add Another" OnClick="addanoFC"/>
                                                    
                                                     <%--data-toggle="modal" data-target="#myModal"--%>
                                          </div>
                                    
                                          </div>                                    
                                               
                            </div>

                                   
                                </div>

                
                                 </div>
                 
                       </div>
     </div>
                
</asp:Content>
